# Generated by Django 5.1.9 on 2025-12-02 20:39

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.indexes import GistIndex
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('ekoh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contextanalysislog',
            new_name='context_ana_entity__5abedb_idx',
            old_name='context_ana_entity__160666_idx',
        ),
        migrations.RenameIndex(
            model_name='scorehistory',
            new_name='score_histo_changed_cca210_idx',
            old_name='score_histo_changed_18e608_idx',
        ),
        migrations.AlterField(
            model_name='confidentialitysetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userethicsscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        # Use GistIndex for LTree
        migrations.AddIndex(
            model_name='expertisecategory',
            index=GistIndex(
                fields=['path'], 
                name='idx_cat_path', 
                opclasses=['gist_ltree_ops']
            ),
        ),
    ]