version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ekoh
      POSTGRES_PASSWORD: ekoh
      POSTGRES_DB: ekoh
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kafka:
    image: vectorized/redpanda:v23.2.13
    command: |
      redpanda start --advertise-kafka-addr=localhost:9092 \
                     --smp 1 --memory 512M --reserve-memory 0M
    ports:
      - "9092:9092"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    command: >
      bash -c "
        poetry run python manage.py migrate &&
        poetry run python manage.py runserver 0.0.0.0:8000
      "
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - db
      - redis
      - kafka
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    command: >
      bash -c "
        poetry run celery -A config worker
        --loglevel=info --concurrency=4
      "
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - db
      - redis
      - kafka

  beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    command: >
      poetry run celery -A config beat
      --loglevel=info
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - worker

volumes:
  db_data:
