[tool.ruff]
target-version = "py312"
line-length = 100
exclude = ["migrations"]

# Enable common linting rules, disable ones Black already covers
select = ["E", "F", "I", "N", "W", "DJ"]
ignore = [
  "E501",  # line length handled by Black
  "DJ001", # model-meta-verbose-name not required everywhere
]

[tool.ruff.isort]
known-first-party = ["konnaxion"]
combine-as-imports = true
force-single-line = false
